common: &common
  adapter: postgresql
  port: 5432
  encoding: unicode
  pool: 5
  host: localhost
  #username: Tung
  #password:

development:
  <<: *common
  database: tstrap_development

test:
  <<: *common
  database: tstrap_test

production:
  <<: *common
  database: tstrap_production
